apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: ceph-csi-operator
        git:
          url: https://github.com/ceph/csi-operator
          ref: v0.6.0
        includePaths:
          - deploy/charts/ceph-csi-operator/templates/*-crd.yaml
