apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: trust-manager
        git:
          url: https://github.com/cert-manager/trust-manager
          ref: v0.22.1
        includePaths:
          - deploy/crds/*.yaml
