---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        githubRelease:
          slug: controlplaneio-fluxcd/flux-operator
          tag: v0.49.0
          assetNames:
            - install.yaml
          disableAutoChecksumValidation: true
