apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: onepassword-connect
        git:
          url: https://github.com/onepassword/connect-helm-charts
          ref: connect-2.4.1
        includePaths:
          - charts/connect/crds/onepassworditem-crd.yaml
