---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/bjw-s-labs/helm-charts
          ref: common-5.0.1
        includePaths:
          - charts/library/common/values.schema.json
          - charts/library/common/schemas/*.json
